/* design/icons-sprite.svg  ->  src/icons-sprite.js
 *
 * The sprite is authored as a real .svg so it can be opened, previewed and diffed
 * as a drawing. The app needs it as a string it can inject once at the root. This
 * generates that string rather than keeping a second hand-maintained copy, which
 * is the only way the preview and the game are guaranteed to show the same marks.
 *
 * Run after editing the sprite:  node design/build-sprite.mjs
 * Verified by game-core/icons.test.cjs, which fails if the two have drifted.
 */
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const here = dirname(fileURLToPath(import.meta.url));
const svg = readFileSync(join(here, "icons-sprite.svg"), "utf8");
const ids = [...svg.matchAll(/<symbol id="i-([^"]+)"/g)].map((m) => m[1]);
if (!ids.length) throw new Error("no symbols found in icons-sprite.svg");

const out = `// GENERATED by design/build-sprite.mjs from design/icons-sprite.svg — do not edit.
// Re-run that script after changing the sprite; game-core/icons.test.cjs fails if you forget.
export const ICON_IDS = ${JSON.stringify(ids)};
export const ICON_SPRITE = ${JSON.stringify(svg)};
`;
writeFileSync(join(here, "..", "src", "icons-sprite.js"), out);
console.log(`wrote src/icons-sprite.js — ${ids.length} icons`);
