/* design/*.css -> src/chronicle-css.js
 *
 * The app has no stylesheet pipeline — it is one JSX file with inline styles and
 * a couple of <style> blocks. So the Chronicle ships as a string injected once,
 * generated from the same files the preview uses. One definition, two consumers.
 *
 *   node design/build-css.mjs
 * Guarded by game-core/chronicle.test.cjs, which fails if this was not re-run.
 */
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(here, f), "utf8");
const css = [read("tokens.css"), read("shell.css"), read("panels.css"), read("sheets.css"), read("combat.css")].join("\n");
writeFileSync(join(here, "..", "src", "chronicle-css.js"),
  `// GENERATED by design/build-css.mjs from design/tokens.css + design/combat.css — do not edit.\n` +
  `export const CHRONICLE_CSS = ${JSON.stringify(css)};\n`);
console.log(`wrote src/chronicle-css.js — ${Math.round(css.length / 1024)} KB`);
