-- Phantom gear: a pool of items pre-generated by the REAL client generateItem() (run outside
-- React in Node), listed by a SQL cron — same pattern as material stacks, no Edge Function.
create table if not exists phantom_gear_pool (
  id   uuid primary key default gen_random_uuid(),
  data jsonb not null,
  ilvl int
);
alter table phantom_gear_pool enable row level security; -- no policies: not client-readable

create or replace function ah_phantom_supply_gear(p_floor int default 14)
returns int language plpgsql security definer set search_path = public, pg_temp as $$
declare v_have int; v_need int; r record; v_base bigint; v_lo bigint; v_hi bigint; v_price bigint; v_item_id uuid; v_data jsonb; n int := 0;
begin
  select count(*) into v_have from ah_listing where status='active' and phantom and kind='gear';
  v_need := greatest(0, p_floor - v_have);
  for r in select data from phantom_gear_pool order by random() limit v_need loop
    v_data := jsonb_set(r.data, '{id}', to_jsonb(gen_random_uuid()::text));
    v_base := ah_gear_base_value(v_data);
    select lo, hi into v_lo, v_hi from ah_band(v_base);
    v_price := least(v_hi, greatest(v_lo, round(v_base * (0.8 + random()*0.5))::bigint));
    insert into item(owner_id, data, bound) values (null, v_data, false) returning id into v_item_id;
    insert into ah_listing(seller_id, kind, item_id, price, base_value, deposit, phantom, expires_at)
      values (null, 'gear', v_item_id, v_price, v_base, 0, true, now() + make_interval(mins => (30 + floor(random()*120))::int));
    n := n + 1;
  end loop;
  return n;
end $$;
revoke all on function ah_phantom_supply_gear(int) from public;

select cron.schedule('ah-gear', '*/5 * * * *', $$select ah_phantom_supply_gear(14);$$)
  where not exists (select 1 from cron.job where jobname='ah-gear');
-- Pool rows: see seed_phantom_gear_pool.sql (generated by the client's generateItem()).
